# Usage:
#   conda env create --name <name> --file environment.yml
# or:
#   conda env create --prefix <path> --file environment.yml

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.10
  - pip
  - numpy
  - netcdf4
  - pyaml
  - jinja2
  # The conda eccodes package delivers the binary library
  - eccodes
  - pip:
    # Install mpi4py from source (sdist at PyPI), this makes sure it is build
    # against system MPI
    - mpi4py
    # eccodes from PyPI delivers the Python bindings
    - eccodes
