# Usage:
#   conda env update --name <name> --file environment-plot.yml
# or:
#   conda env update --prefix <path> --file environment-plot.yml

channels:
  - conda-forge
  - nodefaults

dependencies:
  - cartopy
